<?php

  /**
   * @file
   * Allows users to reserve and checkout nodes
   *
   */


  /**
   * Implementation of hook_menu().
   */
function lending_menu() {
  $items['admin/settings/lending'] = array(
    'title' => 'Lending Library settings',
    'description' => 'Change how lending behaves.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lending_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'lending.admin.inc',
  );
  return $items;
}

/**
 * implementation of hook_perm()
 */
function lending_perm() {
  return array(LEND_ACCESS, LEND_ADMIN);
}


/**
 * Implementation of hook_init() to seperate out code into logical files
 */

function lending_init() {
  require_once('./' . drupal_get_path('module', 'lending') . '/lending-api.inc');
  require_once('./' . drupal_get_path('module', 'lending') . '/lending-checkout.inc');
  require_once('./' . drupal_get_path('module', 'lending') . '/lending-current.inc');
  require_once('./' . drupal_get_path('module', 'lending') . '/lending-request.inc');
  require_once('./' . drupal_get_path('module', 'lending') . '/lending-request-queue.inc');
}

/**
* Implementation of hook_nodeapi().
*
* We display a form on items
*/
function lending_nodeapi(&$node, $op, $teaser, $page) {
  global $user;

  if (lending_not_user_or_admin($user)) {
    return;
  }

  if (lending_not_acceptable_type($node)) {
    return;
  }

  // page must be set otherwise this is a listing
  if (!$page) {
    return;
  }

  switch ($op) {
    // The 'view' operation means the node is about to be displayed.
    case 'view':
      lending_show_lending_panel(&$node);
      break;
  }
}


function lending_show_lending_panel(&$node) {
  // show_current_lender
  // show_lending_queue
  // show_lending_form
  lending_show_current_lender(&$node);

  if (lending_is_admin($user)) {
    lending_show_checkout_form(&$node);
  }
  lending_show_request_queue(&$node);
  lending_show_request_form(&$node);
}

/**
 *  Checkout form
 */

function lending_theme() {
  $path = drupal_get_path('module', 'lending');
  $base = array(
    'path' => "$path/theme"
  );

  $themes = array(
    'lending_user' => $base + array(
      'template' => 'lending-current-lender',
      'arguments' => array('lendee' => NULL, 'checkout' => NULL)
    ),
    'lending_request_queue' => $base + array(
      'template' => 'lending-request-queue',
      'arguments' => array('queue' => array(), 'node' => NULL, 'user' => NULL)
    ),
  );
  return $themes;
}

/**
 * Implementation of hook_views_api.
 */
function lending_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'lending') . '/includes',
  );
}