<?php

  /**
   * @file
   * This module is designed to provide a simple lending interface for
   * checking out or requesting nodes.
   *
   * @note
   * The README.txt in the module contains a sample workflow.
   *
   */


  /**
   * Implementation of hook_menu().
   */
function lending_menu() {
  $items['admin/lending/settings'] = array(
    'title' => 'Lending Library settings',
    'description' => 'Change how lending behaves.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('lending_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'includes/lending.admin.inc',
  );
  return $items;
}

/**
 * implementation of hook_perm()
 */
function lending_perm() {
  return array(LEND_ACCESS, LEND_ADMIN);
}


/**
 * Implementation of hook_init() to seperate out code into logical files for
 * each type of function.
 *
 *  * lending.api.inc - the database interfaces for the two types as well as
 *    permissions
 *  * lending.checkout.inc - the form to do a checkout, and all the logic for
 *    form submission
 *  * lending.current.inc - the code to display the currently lendee
 *  * lending.request.inc - the code to handle user requests
 *  * lending.request-queue.inc - functions handling display of all the
 *    request for an item that are outstanding
 */

function lending_init() {
  require_once('./' . drupal_get_path('module', 'lending') . '/includes/lending.api.inc');
  require_once('./' . drupal_get_path('module', 'lending') . '/includes/lending.checkout.inc');
  require_once('./' . drupal_get_path('module', 'lending') . '/includes/lending.current.inc');
  require_once('./' . drupal_get_path('module', 'lending') . '/includes/lending.request.inc');
  require_once('./' . drupal_get_path('module', 'lending') . '/includes/lending.request-queue.inc');
}

/**
* Implementation of hook_nodeapi().
*
* All the user visible portions of the display are on the nodes for the
* lendable content.
*/
function lending_nodeapi(&$node, $op, $teaser, $page) {
  global $user;

  if ($op == 'delete') {
    lending_cleanup_records(&$node);
    return;
  }

  if ($op == 'view') {
    if (lending_not_user_or_admin($user)) {
      return;
    }

    if (lending_not_acceptable_type($node)) {
      return;
    }

    // we only opperate in page context, so don't display otherwise.
    //
    // TODO: perhaps there is value in displaying in a non page context
    if (!$page) {
      return;
    }

    lending_show_lending_panel(&$node);
  }
}

/**
 * all the functions here are in include files
 */
function lending_show_lending_panel(&$node) {
  lending_show_current_lender(&$node);

  if (lending_is_admin($user)) {
    lending_show_checkout_form(&$node);
  }
  lending_show_request_queue(&$node);
  lending_show_request_form(&$node);
}

/**
 *
 */
function lending_cleanup_records(&$node) {
  lending_delete_requests_by_nid($node->nid);
  lending_delete_checkouts_by_nid($node->nid);
}

/**
 *  Implementation of hook_theme().
 */
function lending_theme() {
  $path = drupal_get_path('module', 'lending');
  $base = array(
    'path' => "$path/theme"
  );

  // TODO: get forms in here as well, though I was having an issue getting
  // them to take parameters as well as the form parameters
  $themes = array(
    'lending_user' => $base + array(
      'template' => 'lending-current-lender',
      'arguments' => array('lendee' => NULL, 'checkout' => NULL)
    ),
    'lending_request_queue' => $base + array(
      'template' => 'lending-request-queue',
      'arguments' => array('queue' => array(), 'node' => NULL, 'user' => NULL)
    ),
  );
  return $themes;
}

/**
 * Implementation of hook_views_api().
 */
function lending_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'lending') . '/includes',
  );
}